<?php
/**
 * @file
 * Contains the geofield_gmap.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function geofield_gmap_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.geofield_gmap':
      $output .= '<h3>' . t('Geofield Gmap About') . '</h3>';
      $output .= '<p>' . t('Google Map widget for Geofield.') . '</p>';
      $output .= '<p>' . t('Allow to use a google map v3 map to input a location.') . '</p>';
      $output .= '<p>' . t('A quick text input + geocode allow you to specify an address.') . '</p>';
      $output .= '<p>' . t('You can drag and drop the marker to narrow the position.') . '</p>';
      $output .= '<p>' . t('For more info: @readme', [
        '@readme' => Link::fromTextAndUrl(t('Readme.md'), Url::fromUri('base:/' . drupal_get_path('module', 'geofield_gmap') . '/README.md', ['attributes' => ['target' => '_blank']]))->toString(),
      ]) . '</p>';

  }
  return $output;
}
